name: google_maps_flutter_example
description: Demonstrates how to use the google_maps_flutter plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  google_maps_flutter:
    # path: ../
    git:
      url: https://github.com/Milvintsiss/plugins.git
      ref: fork-2.2.1
      path: packages/google_maps_flutter/google_maps_flutter
  google_maps_flutter_android:
    # path: ../../google_maps_flutter_android
    git:
      url: https://github.com/Milvintsiss/plugins.git
      ref: fork-2.2.1
      path: packages/google_maps_flutter/google_maps_flutter_android
  google_maps_flutter_platform_interface:
    # path: ../../google_maps_flutter_android
    git:
      url: https://github.com/Milvintsiss/plugins.git
      ref: fork-2.2.1
      path: packages/google_maps_flutter/google_maps_flutter_platform_interface

dev_dependencies:
  espresso: ^0.1.0+2
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
